package com.example.banksampah;

import java.util.ArrayList;

public class NewsData {
    private static String[] titleNews= {
            "Nelayan Padang Kumpulkan 12 Ton Sampah dari Laut dan Pantai",
            "Pemko Padang Gelar Tim OTT untuk Atasi Pembuangan Sampah Sembarangan",
            "Sampah Serapah di Pantai Padang: Dampak Kelakuan Manusia",
            "Inovasi Daur Ulang: Solusi Lingkungan untuk Limbah Plastik",
            "Teknologi Cerdas dalam Manajemen Sampah Kota: Efisiensi dan Kualitas Hidup",
            "Krisis Sampah Plastik: Negara-negara Berkolaborasi Kurangi Polusi",
            "Edukasi Masyarakat: Sampah Buang di Tempatnya untuk Lingkungan Bersih",
            "Daur Ulang: Kiat Mengubah Sampah Menjadi Harta"

    };

    private static String[] detailNews = {
            "Nelayan di Pantai Padang baru-baru ini melakukan aksi luar biasa dalam upaya menjaga lingkungan mereka. Dalam beberapa minggu terakhir, mereka telah berhasil mengumpulkan sekitar 12 ton sampah dari laut dan pantai sekitar kota. Ini adalah bukti konkret komitmen nelayan Padang terhadap perlindungan lingkungan mereka, sementara juga mengungkapkan besarnya tantangan yang dihadapi oleh wilayah pesisir akibat sampah laut.\nTidak hanya merupakan pencapaian penting dalam menjaga lingkungan, pengumpulan sampah oleh nelayan juga mencerminkan dampak perubahan iklim dan aktivitas manusia pada ekosistem laut. Sampah yang terakumulasi di perairan dan pantai telah menjadi masalah global yang mendesak.\nPara nelayan bekerja keras untuk mengumpulkan sampah dari laut dan pantai. Mereka menggunakan peralatan sederhana seperti jaring dan kapal nelayan tradisional untuk mengumpulkan sampah-sampah ini yang berkisar dari plastik hingga sampah organik. Dalam prosesnya, mereka juga mendapatkan dukungan dari komunitas lokal dan organisasi lingkungan.\nUpaya nelayan ini telah mendapat pujian luas dari warga Padang dan otoritas setempat. Ini juga menyoroti pentingnya pendidikan lingkungan yang lebih luas dan tindakan kolektif dalam mengatasi masalah sampah laut.\nMeskipun tindakan nelayan Padang merupakan langkah positif, masalah sampah laut tetap menjadi tantangan yang sangat besar. Itu menggarisbawahi perlunya tindakan serius dalam mengurangi produksi sampah plastik dan mengembangkan sistem pengelolaan sampah yang lebih efisien.",

            "Keprihatinan terhadap perilaku pembuangan sampah sembarangan di Kota Padang telah memicu respons tegas dari Pemerintah Kota (Pemko). Mereka baru-baru ini meluncurkan tim Operasi Tangkap Tangan (OTT) yang bertugas untuk mengawasi dan menindak pelanggaran pembuangan sampah sembarangan.\nTim OTT, yang terdiri dari petugas yang dilatih, telah ditempatkan di seluruh wilayah kota, termasuk tingkat kelurahan. Mereka melakukan patroli rutin untuk memantau dan menindak pelaku pembuangan sampah sembarangan. Pelanggar akan dikenai sanksi berupa denda dan sanksi lainnya.\nPerilaku pembuangan sampah sembarangan telah menjadi masalah yang meresahkan di banyak kota, termasuk Padang. Ini bukan hanya masalah estetika, tetapi juga masalah kesehatan masyarakat dan lingkungan. Pembuangan sampah sembarangan dapat menyebabkan polusi lingkungan, menyebabkan banjir, dan mengancam ekosistem lokal.\nPemko Padang berharap bahwa langkah ini akan mengubah perilaku warga dan mengurangi pembuangan sampah sembarangan. Selain tindakan penindakan, mereka juga menggencarkan kampanye edukasi tentang pentingnya menjaga kebersihan kota dan membuang sampah pada tempatnya.\nRespons Pemko Padang ini adalah langkah positif dalam mengatasi masalah serius ini. Namun, tantangan sejati adalah mengubah kesadaran masyarakat dan memastikan bahwa tindakan ini berkelanjutan dalam jangka panjang.",

            "Keindahan pantai di Padang telah tercemar oleh sampah serapah yang banyak ditemukan di sepanjang garis pantai. Dampak dari perilaku sembrono manusia dalam membuang sampah sembarangan mulai terasa. Sampah tersebut tidak hanya mengganggu keindahan alam, tetapi juga mengancam kehidupan laut dan ekosistem pesisir.\nSampah yang mencakup plastik, styrofoam, dan berbagai jenis limbah lainnya telah menumpuk di pantai Padang. Ini menciptakan masalah lingkungan yang serius, termasuk polusi laut, bahaya bagi satwa laut, dan kerusakan ekosistem pesisir.\nBahkan ketika terlihat sebagai masalah lokal, sampah serapah di pantai Padang mencerminkan masalah global yang lebih besar. Sampah plastik telah menjadi ancaman serius terhadap ekosistem laut di seluruh dunia. Mikroplastik yang terurai dari sampah plastik dapat meracuni air dan makanan laut, dengan dampak berbahaya pada kesehatan manusia.\nPemko Padang dan organisasi lingkungan setempat telah bekerja keras untuk membersihkan pantai dan mengedukasi masyarakat tentang pentingnya menjaga kebersihan pantai. Namun, masalah sampah serapah ini akan terus menjadi tantangan besar jika perilaku manusia tidak berubah secara fundamental.",

            "Dalam era modern yang semakin menyadari dampak negatif polusi plastik, inovasi dalam daur ulang limbah plastik telah menjadi fokus utama. Solusi inovatif ini adalah tonggak besar dalam upaya mengurangi jejak lingkungan plastik dan menciptakan lingkungan yang lebih bersih dan lestari. Dengan penggunaan teknologi tinggi, berbagai solusi kreatif telah muncul yang mendorong pemanfaatan kembali sampah plastik.\nSalah satu inovasi utama adalah pengembangan proses daur ulang yang lebih efisien. Proses daur ulang yang lebih canggih dapat memproses plastik bekas menjadi produk yang lebih berharga, seperti serat tekstil, bahan konstruksi, atau bahkan bahan bakar. Ini bukan hanya mengurangi limbah plastik di tempat pembuangan sampah, tetapi juga mengurangi kebutuhan akan plastik baru.\nSelain itu, inovasi juga mencakup penggunaan bahan daur ulang dalam produk-produk sehari-hari. Perusahaan makanan dan minuman, misalnya, semakin beralih ke kemasan yang lebih ramah lingkungan. Ini bukan hanya memberikan peluang bisnis yang berkelanjutan, tetapi juga mengurangi dampak sampah plastik terhadap lingkungan.\nInovasi dalam daur ulang plastik juga melibatkan pemanfaatan teknologi. Penciptaan mesin pintar yang dapat mengidentifikasi, memisahkan, dan memproses limbah plastik secara otomatis telah mengubah cara daur ulang dilakukan. Ini meningkatkan efisiensi dan memungkinkan daur ulang menjadi lebih terjangkau.\nSelain perkembangan teknologi, kesadaran akan masalah polusi plastik juga mendorong kolaborasi antara pemerintah, perusahaan, dan masyarakat sipil. Semakin banyak organisasi yang berusaha mencari solusi inovatif dan berkolaborasi dalam mengurangi penggunaan plastik sekali pakai. Inovasi dalam daur ulang plastik adalah langkah penting dalam menciptakan dunia yang lebih bersih dan lebih berkelanjutan.",

            "Manajemen sampah kota adalah aspek krusial dalam memelihara kebersihan dan kualitas hidup warga kota. Dalam beberapa tahun terakhir, penggunaan teknologi cerdas telah mengubah cara kota-kota mengelola sampah mereka. Teknologi ini tidak hanya meningkatkan efisiensi pengumpulan dan pengolahan sampah, tetapi juga berkontribusi pada peningkatan kualitas hidup warga kota.\nSalah satu inovasi utama adalah penggunaan sensor pintar pada tempat sampah umum. Sensor ini memungkinkan pengawasan real-time terhadap tingkat pengisian tempat sampah, memungkinkan pengambilan sampah yang lebih efisien. Hal ini mengurangi kemacetan lalu lintas yang diakibatkan oleh pengumpulan sampah dan mengurangi emisi kendaraan pengangkut sampah.\nTeknologi cerdas juga digunakan dalam pengelolaan limbah yang lebih efisien. Sistem manajemen yang terotomatisasi memantau aliran sampah, memilih jalur pengiriman yang paling efisien, dan bahkan memilah sampah secara otomatis. Hasilnya adalah pengurangan biaya operasional dan peningkatan efisiensi.\nSelain itu, teknologi juga memainkan peran penting dalam pendidikan dan kesadaran masyarakat tentang manajemen sampah yang lebih baik. Aplikasi seluler dan platform online menyediakan informasi tentang jadwal pengumpulan sampah, lokasi tempat pembuangan sampah yang terdekat, dan bahkan panduan daur ulang. Semua ini membantu masyarakat menjadi lebih terlibat dalam upaya pengelolaan sampah yang lebih baik.\nPenggunaan teknologi cerdas dalam manajemen sampah kota adalah langkah penting menuju kualitas hidup yang lebih baik dan lingkungan yang lebih bersih di kota-kota di seluruh dunia.",

            "Krisis sampah plastik telah menjadi salah satu tantangan lingkungan global terbesar yang dihadapi manusia saat ini. Plastik yang terbuang sembarangan telah mencemari lautan, sungai, dan lingkungan daratan di seluruh dunia. Dalam menangani masalah ini, negara-negara telah mulai berkolaborasi untuk mengurangi polusi plastik dan mencari solusi bersama.\nSalah satu langkah penting adalah perjanjian internasional tentang pengelolaan sampah plastik. Negara-negara telah memulai perundingan untuk membuat perjanjian global yang bertujuan mengurangi penggunaan plastik sekali pakai, meningkatkan daur ulang, dan mengurangi limbah plastik yang mencemari lingkungan.\nSelain itu, banyak negara telah mengambil langkah-langkah nasional untuk mengurangi polusi plastik. Beberapa negara telah melarang atau mengurangi penggunaan kantong plastik sekali pakai, sedangkan yang lain telah memperkenalkan pajak atau biaya tambahan pada produk plastik.\nIndustri juga berperan penting dalam mengatasi krisis plastik ini. Banyak perusahaan telah berkomitmen untuk mengurangi penggunaan plastik dan meningkatkan daur ulang. Mereka juga berpartisipasi dalam inisiatif global yang bertujuan untuk menghentikan pembuangan sampah plastik ke laut.\nKrisis sampah plastik memerlukan tindakan segera dan tindakan bersama dari seluruh dunia. Kolaborasi antarnegara dan komitmen bersama dari semua pihak merupakan kunci untuk mengurangi polusi plastik dan menjaga planet kita agar tetap lestari. Dengan tindakan yang tepat, kita dapat mengatasi masalah ini dan mencegah dampak buruknya pada lingkungan dan kesehatan manusia.",

            "Pentingnya mendidik masyarakat tentang penanganan sampah dan lingkungan yang bersih semakin terasa di era saat ini. Dalam upaya untuk mencapai lingkungan yang lebih bersih, program edukasi masyarakat tentang kebijakan pengelolaan sampah telah menjadi kunci dalam menciptakan kesadaran dan perubahan perilaku yang diperlukan.\nProgram-program edukasi ini fokus pada pentingnya membuang sampah pada tempatnya, pemilahan sampah, dan pengurangan penggunaan plastik sekali pakai. Masyarakat diajari tentang dampak negatif dari pembuangan sampah sembarangan dan bagaimana perilaku ini dapat merusak lingkungan dan kesehatan masyarakat.\nSelain itu, pendidikan juga melibatkan promosi praktik-praktik berkelanjutan seperti daur ulang dan pengurangan limbah. Sekolah, komunitas, dan organisasi lingkungan aktif dalam membangun kesadaran ini melalui kampanye-kampanye kesadaran dan program-program pendidikan.\nKunci dari program ini adalah mengenalkan konsep tanggung jawab bersama terhadap lingkungan. Masyarakat diberdayakan untuk mengambil peran aktif dalam menjaga kebersihan lingkungan mereka, sehingga menciptakan lingkungan yang lebih bersih dan lebih sehat bagi semua.\nEdukasi masyarakat tentang pengelolaan sampah yang baik juga memiliki manfaat ekonomi. Ketika masyarakat memahami nilai daur ulang dan penggunaan kembali barang-barang yang tidak terpakai, mereka dapat menghasilkan uang dari mengumpulkan dan menjual barang-barang bekas. Hal ini bukan hanya mengurangi jumlah sampah yang masuk ke tempat pembuangan sampah, tetapi juga memberikan peluang ekonomi bagi masyarakat.\nProgram-program edukasi ini bukan hanya membantu menciptakan lingkungan yang lebih bersih dan lebih hijau, tetapi juga berpotensi meningkatkan kualitas hidup masyarakat secara keseluruhan. Semakin banyak masyarakat yang teredukasi, semakin besar kemungkinan kita menciptakan dunia yang lebih bersih dan berkelanjutan.",

            "Daur ulang merupakan salah satu kunci utama dalam mengelola sampah dan melawan polusi lingkungan. Ini adalah cara efektif untuk mengurangi sampah yang masuk ke tempat pembuangan sampah dan mengubah sampah menjadi sumber daya yang berharga. Melalui inovasi dan kiat daur ulang, banyak orang dan organisasi telah mengubah sampah menjadi harta.\nSalah satu kiat daur ulang yang sukses adalah pemisahan sampah di sumbernya. Ini mencakup pemisahan sampah organik, kertas, plastik, logam, dan kaca sejak awal. Dengan memisahkan sampah, kita dapat memastikan bahwa barang-barang yang dapat didaur ulang tidak tercampur dengan sampah lainnya, sehingga meningkatkan kemungkinan untuk daur ulang yang sukses.\nKreativitas juga memainkan peran penting dalam daur ulang. Banyak seniman dan pengrajin telah menggunakan barang-barang bekas untuk membuat karya seni dan barang-barang yang unik. Ini tidak hanya mengurangi limbah, tetapi juga memberikan nilai tambah kepada barang-barang yang sebelumnya dianggap sebagai sampah.\nPentingnya mendukung dan mengembangkan pasar untuk barang-barang daur ulang juga harus ditekankan. Hal ini mencakup mempromosikan produk daur ulang dan mendukung bisnis daur ulang lokal. Dengan meningkatkan permintaan terhadap produk daur ulang, kita dapat menciptakan insentif ekonomi untuk lebih banyak orang terlibat dalam daur ulang.\nSelain itu, inovasi dalam teknologi daur ulang juga berperan besar. Proses daur ulang yang lebih canggih dapat memproses limbah dengan lebih efisien, memungkinkan daur ulang yang lebih luas. Teknologi juga membantu dalam memantau jejak lingkungan produk daur ulang, memastikan bahwa daur ulang adalah pilihan yang ramah lingkungan.\nDalam upaya untuk mengubah sampah menjadi harta, kesadaran masyarakat dan dukungan pemerintah dan industri sangat penting. Dengan tindakan kolektif, kita dapat mengurangi jumlah sampah yang masuk ke tempat pembuangan sampah dan menciptakan masyarakat yang lebih berkelanjutan. Daur ulang adalah langkah penting dalam mengarahkan kita ke masa depan yang lebih bersih dan lebih hijau."
    };

    private static int[] imageNews = {
            R.drawable.image5,
            R.drawable.image6,
            R.drawable.image7,
            R.drawable.image8,
            R.drawable.image9,
            R.drawable.image10,
            R.drawable.image11,
            R.drawable.image12
    };

    static ArrayList<News> getListData(){
        ArrayList<News> list = new ArrayList<>();
        for(int position = 0; position <titleNews.length; position++){
            News news = new News();
            news.setTitle(titleNews[position]);
            news.setDetail(detailNews[position]);
            news.setPhoto(imageNews[position]);
            list.add(news);

        }
        return list;
    }
}
